source 'https://rubygems.org'

#gem 'byebug', group: [:development, :test]
#gem 'json-schema', :git => 'https://github.com/GrooveStomp/json-schema', :branch => 'error-messages'
gem 'minitest'
gem 'minitest-reporters'
gem 'httparty'
#gem 'httmultiparty'
#gem 'minitest/spec'
#gem 'minitest/autorun'
#gem 'minitest/reporters'
#gem 'parallel'
#gem 'rake',         '10.4.2'
#gem 'sequel',       '4.22.0'
#gem 'mysql2',       '0.3.18'
#gem 'json-schema',  :git => 'https://github.com/GrooveStomp/json-schema', :branch => 'error-messages'
gem 'rake'
